---
title: Fun with R
author: CalebCoulson
date: '2021-05-25'
slug: fun-with-r
categories:
  - Basic
tags: []
---


## Variabels and numbers

```{r}
x <- 1
y = 2
3 -> z
x+y
y*z
y/x

```

## Vectors
```{r}
a <- 0:10
print(a)
b<- 10:4
print(b)
class(a)
str(a)
a[c(1,5,10)]
head(a, 4)
tail(b, 5)
```

## Combie operator for creatting vectors
when we create a vector with muultiple data types, R corrects the vector to the most compatable data type
```{r}
c <- c(1:5, 10.5, 'yellow', 'red', 'green')
print(c)
class(c)
str(c)
remove(d)
d<- c(1:5, 10.5)
class(d)
str(d)
```
## Sequence operator Application
```{r}
x <- seq(0, 8*pi, length.out=200)
y <- sin(x)
plot(x,y)
```

## Dropping Missing Values and Summarizing values
```{r}
a<-c(3,-2,4,NA,-1,8,-4,9,NA, 11,3,8,NA)
a[!is.na(a)]
a <-c(2,3,-1,3,5,2,-3,1)
print(paste0("the sum of positive integers in a = ", sum(a[a>0])))
```

## Matrix
```{r}
M1 = matrix(1:12, ncol = 4, byrow = TRUE)
M1
M1[,3]
M2 = matrix(1:12, nrow= 4)
M2
```
## Accesing Matrix elements
```{r}
M1 = matrix(1:20, ncol=4)
M1[c(3,5),c(2,4)]

```
## Data Frames
```{r}
DF <- data.frame(
gender = c("Male", "Male","Female"),
height = c(152, 171.5, 165),
weight = c(81,93, 78),
age =c(42,38,26),
row.names=c('Ally','Belinda','Alfred')
)
DF
DF$age
DF[DF$gender == "Male",]
```


